{{ if .Values.deps.certmanager }}
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
{{ end }}
---
{{ if .Values.deps.nfd }}
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
{{ end }}

