{{ if .Values.local.secret.base64 }}
apiVersion: v1
kind: Secret
metadata:
  name: driver-registry-secret
  namespace: kmm-operator-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "Secret needs a base64 encoded data" .Values.local.secret.base64 }}
{{ end }}
